# Generated by Django 3.2.5 on 2021-12-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitmex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('hour_table_name', models.CharField(max_length=30)),
                ('minute_table_name', models.CharField(max_length=30)),
            ],
        ),
    ]
